networks:
  hytopia-net:
    driver: bridge
    
services:
  hytopia-dev:
    build:
      context: ./dev-server
      dockerfile: Dockerfile
    command: /app/core/utils/setup-env.sh
    stdin_open: true
    tty: true
    ports:
      - "0.0.0.0:${HYTOPIA_PORT:-8080}:8080"
    volumes:
      - ./.env:/app/.env
      - ./dev-server:/app/core
      - ${HYTOPIA_EXAMPLES_PATH:-./examples}:/app/games/examples
      - ${CUSTOM_GAME_PATH:-./game-repos/custom-game}:/app/games/custom-repos
      - ./state:/app/state
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - NODE_ENV=development
      - BUN_ENV=development
      - HYTOPIA_PORT=${HYTOPIA_PORT:-8080}
      - HYTOPIA_EXAMPLES_PATH=${HYTOPIA_EXAMPLES_PATH:-./examples}
      - CUSTOM_GAME_PATH=${CUSTOM_GAME_PATH:-./game-repos/custom-game}
      - ENABLE_OFFICIAL_EXAMPLES=${ENABLE_OFFICIAL_EXAMPLES:-true}
      - ENABLE_CUSTOM_GAME=${ENABLE_CUSTOM_GAME:-true}
      - EXAMPLES=${EXAMPLES:-}
      - GAME_REPOS=${GAME_REPOS:-}
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:-}
      - TUNNEL_ID=${TUNNEL_ID:-}
      - TUNNEL_DOMAIN=${TUNNEL_DOMAIN:-}
    networks:
      hytopia-net:
        aliases:
          - hytopia-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:-}
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - hytopia-net
