networks:
  hytopia-net:
    driver: bridge
    
services:
  hytopia-dev:
    build:
      context: ./dev-server
      dockerfile: Dockerfile
    command: /app/setup-env.sh  # Call setup-env.sh script during container startup
    ports:
      - "${HYTOPIA_PORT:-8080}:8080"
    volumes:
      - ./dev-server:/app/core
      - ${HYTOPIA_EXAMPLES_PATH:-./examples}:/app/games/official-examples
    environment:
      - NODE_ENV=development
      - BUN_ENV=development
      - TUNNEL_DOMAIN=${TUNNEL_DOMAIN:-}  # Default to empty if not set
    networks:
      - hytopia-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:-}  # Default to empty if not set
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - hytopia-net
