tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Default catch-all rule
  - hostname: "${TUNNEL_DOMAIN}"
    service: http://hytopia-dev:8080

  # Dynamic rules for examples
  ${DYNAMIC_EXAMPLES}

  # Dynamic rules for custom repositories
  ${DYNAMIC_ROUTES}

  # Catch-all rule
  - service: http_status:404 